// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Dialog exposes native dialogs to the frontend via generated bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * PickFolder shows a native folder picker and returns the chosen absolute path
 * ("" when the user cancels — not an error).
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(3498263924);
}
